### ISSUE TITLE
Armor Class Poput doesnt dissappear

### ISSUE THREAD

**Issue by vt-tom** [snshatto/deadly-encounter-benchmark#2]
If i hover over the armor class, the AC Value goes left and the popup doesnt dissappear. 

![grafik](https://user-images.githubusercontent.com/80099175/212653326-edcfb001-c141-489a-977a-20598ca72722.png)

(Tried with all modules deactivated despite this)
DnD v 2.0.3
Module v 1.2.3

**Comment by snshatto** [comment]
Thanks for pointing this out! It has been fixed in v1.2.4
